apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    tier: web
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      tier: web
      component: frontend
  template:
    metadata:
      labels:
        project: expense
        tier: web
        component: frontend
    spec:
      containers:
      - name: frontend
        image: chaitanyaj293/frontend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    project: expense
    tier: web
    component: frontend
  ports:
  - name: frontend-svc-port
    protocol: TCP
    port: 80
    targetPort: 80


