apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    tier: api
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      tier: api
      component: backend
  template:
    metadata:
      labels:
        project: expense
        tier: api
        component: backend
    spec:
      containers:
      - name: backend
        image: chaitanyaj293/backend:v1
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    tier: api
    component: backend
  ports:
  - name: backend-svc-port
    protocol: TCP
    port: 8080
    targetPort: 8080



